import { describe, expect, it, vi } from 'vitest';

vi.mock('@mantle/runtime/assistant', () => ({
  runSimulatedResponderTurn: vi.fn(),
  describeResponderPersona: vi.fn(),
}));

import { registerMantleTools } from '../build-server';

/**
 * The MCP surface, pinned exactly and in registration order.
 *
 * registerMantleTools was a single 921-line function; it is now a sequencer
 * over register/*.ts. Cutting it up moved every hand-written `server.tool`
 * block into a different file and turned lexical captures into a destructured
 * context, so the one thing that had to survive untouched is WHAT GETS
 * REGISTERED. Nothing else in the package asserted that: the existing tests
 * pull one handler by name, so a whole registrar could stop being called and
 * they would all still pass.
 *
 * This list was generated from the pre-split implementation and verified equal
 * to the post-split one over both transports before being written down.
 *
 * Order is pinned because MCP clients see the tool list in registration order,
 * and a duplicate slug registered later silently wins.
 *
 * When you deliberately add or remove a tool, this list changes in the same
 * commit. That is the point: the diff shows the surface change.
 */
const HTTP_SURFACE = [
  'tree_list',
  'search',
  'folder_create',
  'folder_delete',
  'file_upload',
  'file_delete',
  'folder_describe',
  'folder_rename',
  'file_move',
  'file_copy',
  'folder_move',
  'folder_copy',
  'file_set_indexing',
  'folder_set_indexing',
  'file_read',
  'file_get',
  'file_rename',
  'pending_list',
  'pending_get',
  'pending_approve',
  'pending_reject',
  'worker_group_list',
  'worker_group_ensure',
  'telegram_pending',
  'telegram_react',
  'telegram_edit',
  'telegram_mark_processed',
  'telegram_pair',
  'note_create',
  'note_update',
  'note_list',
  'note_get',
  'note_from_file',
  'note_from_page',
  'note_delete',
  'task_list',
  'task_get',
  'task_create',
  'task_update',
  'task_delete',
  'task_comments_list',
  'task_comment_add',
  'event_list',
  'event_get',
  'event_create',
  'event_update',
  'event_delete',
  'recall_index',
  'recall_open',
  'recall_go',
  'recall_match',
  'journal_list',
  'journal_get',
  'journal_create',
  'journal_update',
  'journal_resolve_gap',
  'journal_delete',
  'peer_list',
  'peer_query',
  'peer_search_chunks',
  'peer_node_get',
  'email_send',
  'email_page',
  'email_list',
  'email_get',
  'page_list',
  'page_get',
  'page_create',
  'page_from_file',
  'page_from_note',
  'page_from_notes',
  'page_from_journal',
  'page_replace_from_file',
  'page_update',
  'page_update_draft',
  'page_blocks_list',
  'page_block_get',
  'page_block_update',
  'page_block_insert_after',
  'page_block_insert_before',
  'page_block_append',
  'page_block_delete',
  'page_blocks_apply',
  'page_commit',
  'page_discard_draft',
  'page_split',
  'page_extract_section',
  'page_move',
  'page_mention',
  'page_delete',
  'page_share',
  'page_unshare',
  'draw_list',
  'draw_get',
  'table_list',
  'table_get',
  'table_rows_list',
  'table_create',
  'table_from_file',
  'table_from_text',
  'table_update',
  'table_delete',
  'table_commit',
  'table_schema',
  'table_sql',
  'table_row_get',
  'table_query',
  'table_aggregate',
  'table_row_add',
  'table_rows_add',
  'table_rows_upsert',
  'table_row_update',
  'table_row_delete',
  'table_cell_set',
  'table_column_add',
  'table_column_update',
  'table_column_delete',
  'table_tab_add',
  'table_tab_rename',
  'table_tab_delete',
  'table_set_aggregate',
  'table_set_view',
  'contact_find',
  'contact_list',
  'contact_get',
  'contact_create',
  'contact_update',
  'contact_delete',
  'extract_from_image',
  'summarize_text',
  'generate_image',
  'ask_responder',
  'ask_as_responder',
  'export_node',
  'sheet_build',
  'app_create',
  'app_get',
  'app_file_write',
  'app_file_delete',
  'app_source_set',
  'app_build',
  'app_tools_set',
  'app_db_schema_set',
  'app_db_seed',
  'app_table_export_set',
  'app_table_export_remove',
  'app_list',
  'app_publish',
  'app_delete',
  'sandbox_create',
  'sandbox_exec',
  'sandbox_list',
  'sandbox_stop',
  'sandbox_rm',
  'sandbox_export',
  'sandbox_import',
  'sandbox_ls',
  'sandbox_autostart',
  'sandbox_publish',
  'sandbox_mcp_tools',
  'sandbox_mcp_call',
  'node_read',
  'brain_capacity',
  'search_chunks',
  'read_section',
  'entity_search',
  'entity_neighbors',
  'graph_path',
  'entity_facts',
  'entity_mentions',
  'folder_list',
  'file_list',
  'telegram_send',
  'read_result',
  'show_image',
  'app_db_list',
  'app_db_query',
  'calculate',
  'formula_list',
  'formula_get',
  'formula_evaluate',
  'formula_create',
  'formula_update',
  'formula_delete',
  'file_create',
  'folder_get_by_path',
  'content_supersede',
  'process_extraction',
  'find_window',
  'replay_window',
  'team_request_create',
  'team_member_list',
  'team_notify',
  'team_chat_list',
  'team_chat_read',
  'team_access_list',
  'web_search',
  'web_search_pro',
  'video_ingest',
  'web_map',
  'web_crawl',
  'location_save',
  'location_nearby',
  'location_distance',
  'route_map',
  'update_persona',
  'set_timezone',
  'secret_create',
  'node_share',
  'node_unshare',
  'invoke_agent',
  'run_plan',
  'run_append',
  'run_state',
  'run_cancel',
  'run_audit',
  'openrouter_rankings',
  'openrouter_benchmarks',
  'openrouter_task_classes',
  'model_catalog',
  'model_pool_list',
  'model_pool_set',
  'model_pool_remove',
  'recall_eval',
  'web_fetch',
  'api_tool_list',
  'api_tool_get',
  'api_tool_create',
  'api_tool_update',
  'api_tool_delete',
  'api_tool_test',
  'api_key_refs',
  'api_docs_set',
  'api_docs_get',
  'api_skill_set',
  'tool_catalog',
  'recipe_tool_create',
  'recipe_tool_test',
  'tool_group_list',
  'tool_group_ensure',
  'agent_list',
  'agent_grant_tool_group',
];

/** Register onto a capturing fake; the SDK server is not needed to list names. */
function surface(transport: 'stdio' | 'http'): string[] {
  const names: string[] = [];
  registerMantleTools({ tool: (n: string) => void names.push(n) } as never, 'owner-1', {
    transport,
  });
  return names;
}

describe('MCP tool surface', () => {
  it('registers exactly the pinned list, in order, over http', () => {
    expect(surface('http')).toEqual(HTTP_SURFACE);
  });

  it('adds run_terminal over stdio and nothing else', () => {
    // Over stdio the client already spawned the process, so a shell grants
    // nothing new; over HTTP it would turn a stolen bearer into a root shell.
    expect(surface('stdio').filter((s) => !HTTP_SURFACE.includes(s))).toEqual(['run_terminal']);
    expect(surface('stdio').length).toBe(HTTP_SURFACE.length + 1);
  });

  it('registers no slug twice', () => {
    const seen = new Map<string, number>();
    for (const s of surface('stdio')) seen.set(s, (seen.get(s) ?? 0) + 1);
    expect([...seen].filter(([, n]) => n > 1)).toEqual([]);
  });
});
