#!/usr/bin/env bash
#
# Mantle one-line installer — pulls the published Docker image and starts the
# full stack with generated secrets. No manual .env editing needed for a
# localhost install; a domain install is one env var.
#
#   curl -fsSL https://raw.githubusercontent.com/crossworks-engineering/mantle/main/install.sh | bash
#
# Options (env vars, set before the pipe or export first):
#   MANTLE_HOME=~/mantle          install directory          (default: ./mantle)
#   MANTLE_DOMAIN=m.example.com   serve this hostname with automatic HTTPS
#                                 (DNS A record + open ports 80/443 first);
#                                 omit for http://localhost
#   MANTLE_CHANNEL=main           git ref to fetch the deploy bundle from
#                                 (default: main; a release tag like v0.20.66
#                                 pins compose+infra to that release)
#
# What it does — and nothing else:
#   1. checks docker + the compose plugin exist
#   2. downloads the deploy bundle (docker-compose.yml, .env.prod.example,
#      infra/caddy/Caddyfile, infra/postgres/init/*.sql, db scripts)
#   3. generates SESSION_SECRET / MANTLE_MASTER_KEY / POSTGRES_PASSWORD /
#      S3_SECRET_KEY into .env (never overwrites an existing .env)
#   4. docker compose pull && docker compose up -d --wait
#   5. tells you where to sign up
#
# Updating later (see docs/self-hosting.md):
#   cd <MANTLE_HOME> && docker compose pull && docker compose up -d --wait

set -euo pipefail

# MANTLE_REPO_RAW: override for forks/tests (a fork's raw URL, or a local
# http server in CI). MANTLE_SKIP_START=1 scaffolds + writes .env but skips
# the pull/up — used to test the installer without launching a stack.
REPO_RAW="${MANTLE_REPO_RAW:-https://raw.githubusercontent.com/crossworks-engineering/mantle}"
CHANNEL="${MANTLE_CHANNEL:-main}"
HOME_DIR="${MANTLE_HOME:-./mantle}"
DOMAIN="${MANTLE_DOMAIN:-}"
SKIP_START="${MANTLE_SKIP_START:-}"

say()  { printf '\033[1;36m▶ %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m✔ %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31m✘ %s\033[0m\n' "$*" >&2; exit 1; }

# ── 1. prerequisites ─────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "docker is not installed — https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || die "the docker compose plugin is missing — https://docs.docker.com/compose/install/"
docker info >/dev/null 2>&1 || die "the docker daemon isn't running (or you lack permission — add your user to the docker group)"

# Secret generation: openssl when present, /dev/urandom fallback.
gen_secret() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "$bytes"
  else
    head -c "$bytes" /dev/urandom | base64
  fi
}

# ── 2. scaffold + fetch the deploy bundle ────────────────────────────────────
say "Installing Mantle into ${HOME_DIR} (bundle ref: ${CHANNEL})"
mkdir -p "$HOME_DIR/infra/caddy" "$HOME_DIR/infra/postgres/init" "$HOME_DIR/scripts" "$HOME_DIR/data"
cd "$HOME_DIR"

fetch() { # fetch <repo-path> <local-path>
  curl -fsSL "${REPO_RAW}/${CHANNEL}/$1" -o "$2" || die "download failed: $1"
}

fetch docker-compose.yml                 docker-compose.yml
fetch .env.prod.example                  .env.prod.example
fetch infra/caddy/Caddyfile              infra/caddy/Caddyfile
fetch infra/postgres/init/01-extensions.sql  infra/postgres/init/01-extensions.sql
fetch infra/postgres/init/02-auth-schema.sql infra/postgres/init/02-auth-schema.sql
fetch scripts/db-dump.sh                 scripts/db-dump.sh
fetch scripts/db-restore.sh              scripts/db-restore.sh
chmod +x scripts/db-dump.sh scripts/db-restore.sh
ok "deploy bundle fetched"

# ── 3. .env — generate once, never clobber ───────────────────────────────────
if [ -f .env ]; then
  say ".env already exists — keeping it (delete it to regenerate)"
else
  SESSION_SECRET="$(gen_secret 48)"
  MASTER_KEY="$(gen_secret 32)"
  PG_PASS="$(gen_secret 24 | tr -dc 'A-Za-z0-9' | head -c 24)"
  S3_SECRET="$(gen_secret 24 | tr -dc 'A-Za-z0-9' | head -c 24)"
  if [ -n "$DOMAIN" ]; then
    SITE_ADDRESS="$DOMAIN"
    PUBLIC_URL="https://${DOMAIN}"
  else
    SITE_ADDRESS=":80"
    PUBLIC_URL="http://localhost"
  fi
  cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Reference for every knob: .env.prod.example
#
# ⚠ MANTLE_MASTER_KEY encrypts your stored API keys and secrets at rest.
#   Back this file up — losing the key means losing access to the vault.

SESSION_SECRET=${SESSION_SECRET}
MANTLE_MASTER_KEY=${MASTER_KEY}
ALLOWED_USER_ID=

POSTGRES_PASSWORD=${PG_PASS}
S3_ACCESS_KEY=minio
S3_SECRET_KEY=${S3_SECRET}

MANTLE_PUBLIC_URL=${PUBLIC_URL}
MANTLE_SITE_ADDRESS=${SITE_ADDRESS}
MANTLE_DATA_DIR=./data

MANTLE_IMAGE_NAMESPACE=titanwest
MANTLE_IMAGE_TAG=latest
EOF
  chmod 600 .env
  ok ".env written with generated secrets (mode 600)"
fi

# ── 4. pull + start ──────────────────────────────────────────────────────────
if [ -n "$SKIP_START" ]; then
  ok "MANTLE_SKIP_START set — scaffold + .env done; start later with: docker compose up -d --wait"
  exit 0
fi
say "Pulling images (first run downloads ~2 GB)…"
docker compose pull
say "Starting the stack — migrations run first, the embedder model pulls once (~300 MB)…"
docker compose up -d --wait

# ── 5. done ──────────────────────────────────────────────────────────────────
URL="${DOMAIN:+https://$DOMAIN}"; URL="${URL:-http://localhost}"
ok "Mantle is up."
cat <<EOF

  1. Open ${URL} and create your account (first visit → sign up).
  2. The onboarding wizard takes it from there: assistant, API keys,
     email, Telegram — all configured in the interface.

  Your data lives in $(pwd)/data — back it up and it IS your brain.
  Update later:   cd $(pwd) && docker compose pull && docker compose up -d --wait
  Full guide:     https://github.com/crossworks-engineering/mantle/blob/main/docs/self-hosting.md
EOF
