/** Re-export from the shared workspace package. See @mantle/content. */
export {
  DRAWS_ROOT_LABEL,
  EMPTY_SCENE,
  normalizeScene,
  listDraws,
  countDraws,
  listDrawTags,
  getDraw,
  getDrawSvg,
  createDraw,
  updateDraw,
  saveDrawDraft,
  discardDrawDraft,
  commitDraw,
  deleteDraw,
  sceneToText,
  SCENE_SVG_MAX_BYTES,
  type DrawRow,
  type DrawDetail,
  type DrawSort,
  type DrawVisibility,
  type CreateDrawInput,
  type UpdateDrawInput,
  type SaveDrawDraftResult,
  type CommitDrawResult,
} from '@mantle/content';
