/** Re-export from the shared workspace package. See @mantle/content. */
export {
  JOURNAL_ROOT_LABEL,
  KINDS,
  KIND_KEYS,
  USER_KIND_KEYS,
  AGENT_KIND_KEYS,
  GAP_STATUSES,
  listJournals,
  countJournals,
  listJournalTags,
  getJournal,
  createJournal,
  updateJournal,
  deleteJournal,
  resolveGapEntry,
  type JournalRow,
  type KindKey,
  type JournalLane,
  type GapStatus,
  type CreateJournalInput,
  type UpdateJournalInput,
  type ResolveGapInput,
} from '@mantle/content/journal';
