/**
 * Display-font registry — the SINGLE source of truth for the user-selectable
 * wordmark + page-title fonts (Settings → Appearance → Fonts).
 *
 * One list drives everything: the `@font-face` block (generated by
 * `displayFontFaceCss`, injected once in the root layout), the two pickers, and
 * the runtime CSS-var override in `FontProvider`. Add a font in ONE place —
 * drop the face in `public/fonts/library/`, run `node scripts/fonts-to-woff2.mjs
 * --prune <that file>`, mirror the .woff2 into both apps' public dirs, and add a
 * row here. woff2 only — display-fonts.test.ts asserts registry and files agree.
 *
 * Loading is lazy by construction: a browser fetches a font file only when it
 * actually paints text in that family, so declaring ~25 `@font-face` rules costs
 * nothing until a font is *selected* (or previewed while the picker is open) —
 * the runtime cost is the two chosen faces, not the whole library. This is why
 * we can ship variety without eager-bundling every face (unlike `next/font`,
 * which is right for the always-loaded UI font but wrong for an opt-in library).
 *
 * `sans` and `bukhari` are the two defaults and carry no library file: `sans`
 * resolves to the app UI font (`--font-sans`), `bukhari` to the existing
 * next/font wordmark face.
 */

export type FontFallback = 'sans-serif' | 'serif' | 'cursive' | 'monospace';

export type DisplayFont = {
  /** Stable slug stored in preferences + used as the file basename. */
  key: string;
  /** Human label shown in the picker. */
  label: string;
  /** CSS `font-family` name declared by our `@font-face` (or null for the two
   *  built-in defaults, which map to existing families). */
  family: string | null;
  /** Generic fallback appended after the family. */
  fallback: FontFallback;
  /** Public path to the face file, or null for the built-in defaults. */
  file: string | null;
};

/** Default wordmark = the existing Bukhari face; default title = the UI sans. */
export const DEFAULT_LOGO_FONT = 'bukhari';
export const DEFAULT_TITLE_FONT = 'sans';

const LIB = '/fonts/library';

export const DISPLAY_FONTS: DisplayFont[] = [
  // Built-in defaults (no library file).
  { key: 'sans', label: 'System (Inter)', family: null, fallback: 'sans-serif', file: null },
  {
    key: 'bukhari',
    label: 'Bukhari Script',
    family: 'Bukhari Script',
    fallback: 'cursive',
    file: '/fonts/BukhariScript-Regular.woff2',
  },
  // Library — one representative face per family (self-hosted, OFL; licenses in
  // public/fonts/library/licenses/).
  {
    key: 'biorhyme',
    label: 'BioRhyme',
    family: 'BioRhyme',
    fallback: 'serif',
    file: `${LIB}/biorhyme.woff2`,
  },
  {
    key: 'bitcount',
    label: 'Bitcount',
    family: 'Bitcount Prop Double',
    fallback: 'monospace',
    file: `${LIB}/bitcount.woff2`,
  },
  {
    key: 'bungee-shade',
    label: 'Bungee Shade',
    family: 'Bungee Shade',
    fallback: 'sans-serif',
    file: `${LIB}/bungee-shade.woff2`,
  },
  {
    key: 'capriola',
    label: 'Capriola',
    family: 'Capriola',
    fallback: 'sans-serif',
    file: `${LIB}/capriola.woff2`,
  },
  {
    key: 'cinzel-decorative',
    label: 'Cinzel Decorative',
    family: 'Cinzel Decorative',
    fallback: 'serif',
    file: `${LIB}/cinzel-decorative.woff2`,
  },
  {
    key: 'economica',
    label: 'Economica',
    family: 'Economica',
    fallback: 'sans-serif',
    file: `${LIB}/economica.woff2`,
  },
  {
    key: 'fugaz-one',
    label: 'Fugaz One',
    family: 'Fugaz One',
    fallback: 'sans-serif',
    file: `${LIB}/fugaz-one.woff2`,
  },
  {
    key: 'jersey-15',
    label: 'Jersey 15',
    family: 'Jersey 15',
    fallback: 'sans-serif',
    file: `${LIB}/jersey-15.woff2`,
  },
  {
    key: 'la-belle-aurore',
    label: 'La Belle Aurore',
    family: 'La Belle Aurore',
    fallback: 'cursive',
    file: `${LIB}/la-belle-aurore.woff2`,
  },
  {
    key: 'londrina-outline',
    label: 'Londrina Outline',
    family: 'Londrina Outline',
    fallback: 'sans-serif',
    file: `${LIB}/londrina-outline.woff2`,
  },
  {
    key: 'nabla',
    label: 'Nabla',
    family: 'Nabla',
    fallback: 'sans-serif',
    file: `${LIB}/nabla.woff2`,
  },
  {
    key: 'playball',
    label: 'Playball',
    family: 'Playball',
    fallback: 'cursive',
    file: `${LIB}/playball.woff2`,
  },
  {
    key: 'playwrite-ie',
    label: 'Playwrite IE',
    family: 'Playwrite IE',
    fallback: 'cursive',
    file: `${LIB}/playwrite-ie.woff2`,
  },
  {
    key: 'podkova',
    label: 'Podkova',
    family: 'Podkova',
    fallback: 'serif',
    file: `${LIB}/podkova.woff2`,
  },
  {
    key: 'saira-extra-condensed',
    label: 'Saira Extra Condensed',
    family: 'Saira Extra Condensed',
    fallback: 'sans-serif',
    file: `${LIB}/saira-extra-condensed.woff2`,
  },
  {
    key: 'sansation',
    label: 'Sansation',
    family: 'Sansation',
    fallback: 'sans-serif',
    file: `${LIB}/sansation.woff2`,
  },
  {
    key: 'share',
    label: 'Share',
    family: 'Share',
    fallback: 'sans-serif',
    file: `${LIB}/share.woff2`,
  },
  {
    key: 'sofia',
    label: 'Sofia',
    family: 'Sofia',
    fallback: 'cursive',
    file: `${LIB}/sofia.woff2`,
  },
  {
    key: 'warnes',
    label: 'Warnes',
    family: 'Warnes',
    fallback: 'sans-serif',
    file: `${LIB}/warnes.woff2`,
  },
  {
    key: 'yanone-kaffeesatz',
    label: 'Yanone Kaffeesatz',
    family: 'Yanone Kaffeesatz',
    fallback: 'sans-serif',
    file: `${LIB}/yanone-kaffeesatz.woff2`,
  },
  {
    key: 'zen-dots',
    label: 'Zen Dots',
    family: 'Zen Dots',
    fallback: 'sans-serif',
    file: `${LIB}/zen-dots.woff2`,
  },
];

const BY_KEY = new Map(DISPLAY_FONTS.map((f) => [f.key, f]));

export function fontByKey(key: string | null | undefined): DisplayFont | undefined {
  return key ? BY_KEY.get(key) : undefined;
}

/**
 * CSS `font-family` value for a font key — what the wordmark/title elements
 * resolve to. `sans` maps to the app UI font var; everything else is its
 * declared family + generic fallback. Unknown keys → null (caller keeps default).
 */
export function fontFamilyValue(key: string | null | undefined): string | null {
  const f = fontByKey(key);
  if (!f) return null;
  if (f.key === 'sans') return 'var(--font-sans, ui-sans-serif, sans-serif)';
  if (!f.family) return null;
  return `"${f.family}", ${f.fallback}`;
}

/**
 * `@font-face` rules for every library face — injected once server-side in the
 * root layout so the declarations are present on first paint (no FOUT wait) yet
 * the files stay lazily fetched. Deterministic (no runtime state) so it's safe
 * to render into a <style>.
 */
export function displayFontFaceCss(): string {
  return DISPLAY_FONTS.filter((f) => f.file && f.family)
    .map(
      (f) =>
        `@font-face{font-family:"${f.family}";src:url("${f.file}") format("${fileFormat(f.file!)}");font-display:swap;font-style:normal;}`,
    )
    .join('\n');
}

/** `format()` hint for a face file. A wrong hint makes the browser skip the
 *  face entirely, so it is derived from the filename, never assumed. */
function fileFormat(file: string): string {
  if (file.endsWith('.woff2')) return 'woff2';
  if (file.endsWith('.woff')) return 'woff';
  if (file.endsWith('.otf')) return 'opentype';
  return 'truetype';
}

/**
 * Resolve the two stored display-font keys to their CSS `font-family` values,
 * dropping defaults and unknown keys — the shared projection behind the
 * server-rendered `<html>` appearance attributes (see appearance.ts). Values
 * land as inline style on the root element; "default" is the absence of the
 * var, so the elements' var() fallbacks win. There is deliberately NO
 * localStorage / before-paint-script path anymore: the document arrives
 * correct, and the client providers read the rendered attributes back as
 * their initial state.
 */
export type ResolvedFontVars = { wordmark?: string; pageTitle?: string };
export function resolveFontVars(
  logo: string | null | undefined,
  title: string | null | undefined,
): ResolvedFontVars {
  const out: ResolvedFontVars = {};
  if (logo && logo !== DEFAULT_LOGO_FONT) {
    const v = fontFamilyValue(logo);
    if (v) out.wordmark = v;
  }
  if (title && title !== DEFAULT_TITLE_FONT) {
    const v = fontFamilyValue(title);
    if (v) out.pageTitle = v;
  }
  return out;
}
