/**
 * Display-font registry — the SINGLE source of truth for the user-selectable
 * wordmark + page-title fonts (Settings → Appearance → Fonts).
 *
 * One list drives everything: the `@font-face` block (generated by
 * `displayFontFaceCss`, injected once in the root layout), the two pickers, and
 * the runtime CSS-var override in `FontProvider`. Add a font in ONE place —
 * drop the face in `public/fonts/library/`, run `node scripts/fonts-to-woff2.mjs
 * --prune <that file>`, mirror the .woff2 into both apps' public dirs, and add a
 * row here. woff2 only — display-fonts.test.ts asserts registry and files agree.
 *
 * Loading is lazy by construction: a browser fetches a font file only when it
 * actually paints text in that family, so declaring ~25 `@font-face` rules costs
 * nothing until a font is *selected* (or previewed while the picker is open) —
 * the runtime cost is the two chosen faces, not the whole library. This is why
 * we can ship variety without eager-bundling every face (unlike `next/font`,
 * which is right for the always-loaded UI font but wrong for an opt-in library).
 *
 * `sans` and `bukhari` are the two defaults and carry no library file: `sans`
 * resolves to the app UI font (`--font-sans`), `bukhari` to the existing
 * next/font wordmark face.
 */

export type FontFallback = 'sans-serif' | 'serif' | 'cursive' | 'monospace';

/** Which shelf of the UI-font picker a face sits on. */
export type UiFontCategory = 'sans' | 'mono' | 'character';

export type DisplayFont = {
  /** Stable slug stored in preferences + used as the file basename. */
  key: string;
  /** Human label shown in the picker. */
  label: string;
  /** CSS `font-family` name declared by our `@font-face` (or null for the two
   *  built-in defaults, which map to existing families). */
  family: string | null;
  /** Generic fallback appended after the family. */
  fallback: FontFallback;
  /** Public path to the face file, or null for the built-in defaults. */
  file: string | null;
  /** VARIABLE faces must declare their weight range in `@font-face`, or the
   *  browser treats the file as a single 400 and SYNTHESISES bold — which on a
   *  UI font shows up everywhere as smeared headings and buttons. Declared wider
   *  than any real axis on purpose: a range beyond the font's own is clamped to
   *  what the file has, so one honest value beats eleven guesses at each axis. */
  weight?: string;
  /** UI fonts only — the picker's grouping. */
  category?: UiFontCategory;
};

/** Every UI face here is a VARIABLE font, so one file carries every weight. */
const VARIABLE = '100 900';

/** Default wordmark = the existing Bukhari face; default title = the UI sans. */
export const DEFAULT_LOGO_FONT = 'bukhari';
export const DEFAULT_TITLE_FONT = 'sans';

const LIB = '/fonts/library';

export const DISPLAY_FONTS: DisplayFont[] = [
  // Built-in defaults (no library file).
  { key: 'sans', label: 'System (Inter)', family: null, fallback: 'sans-serif', file: null },
  {
    key: 'bukhari',
    label: 'Bukhari Script',
    family: 'Bukhari Script',
    fallback: 'cursive',
    file: '/fonts/BukhariScript-Regular.woff2',
  },
  // Library — one representative face per family (self-hosted, OFL; licenses in
  // public/fonts/library/licenses/).
  {
    key: 'biorhyme',
    label: 'BioRhyme',
    family: 'BioRhyme',
    fallback: 'serif',
    file: `${LIB}/biorhyme.woff2`,
  },
  {
    key: 'bitcount',
    label: 'Bitcount',
    family: 'Bitcount Prop Double',
    fallback: 'monospace',
    file: `${LIB}/bitcount.woff2`,
  },
  {
    key: 'bungee-shade',
    label: 'Bungee Shade',
    family: 'Bungee Shade',
    fallback: 'sans-serif',
    file: `${LIB}/bungee-shade.woff2`,
  },
  {
    key: 'capriola',
    label: 'Capriola',
    family: 'Capriola',
    fallback: 'sans-serif',
    file: `${LIB}/capriola.woff2`,
  },
  {
    key: 'cinzel-decorative',
    label: 'Cinzel Decorative',
    family: 'Cinzel Decorative',
    fallback: 'serif',
    file: `${LIB}/cinzel-decorative.woff2`,
  },
  {
    key: 'economica',
    label: 'Economica',
    family: 'Economica',
    fallback: 'sans-serif',
    file: `${LIB}/economica.woff2`,
  },
  {
    key: 'fugaz-one',
    label: 'Fugaz One',
    family: 'Fugaz One',
    fallback: 'sans-serif',
    file: `${LIB}/fugaz-one.woff2`,
  },
  {
    key: 'jersey-15',
    label: 'Jersey 15',
    family: 'Jersey 15',
    fallback: 'sans-serif',
    file: `${LIB}/jersey-15.woff2`,
  },
  {
    key: 'la-belle-aurore',
    label: 'La Belle Aurore',
    family: 'La Belle Aurore',
    fallback: 'cursive',
    file: `${LIB}/la-belle-aurore.woff2`,
  },
  {
    key: 'londrina-outline',
    label: 'Londrina Outline',
    family: 'Londrina Outline',
    fallback: 'sans-serif',
    file: `${LIB}/londrina-outline.woff2`,
  },
  {
    key: 'nabla',
    label: 'Nabla',
    family: 'Nabla',
    fallback: 'sans-serif',
    file: `${LIB}/nabla.woff2`,
  },
  {
    key: 'playball',
    label: 'Playball',
    family: 'Playball',
    fallback: 'cursive',
    file: `${LIB}/playball.woff2`,
  },
  {
    key: 'playwrite-ie',
    label: 'Playwrite IE',
    family: 'Playwrite IE',
    fallback: 'cursive',
    file: `${LIB}/playwrite-ie.woff2`,
  },
  {
    key: 'podkova',
    label: 'Podkova',
    family: 'Podkova',
    fallback: 'serif',
    file: `${LIB}/podkova.woff2`,
  },
  {
    key: 'saira-extra-condensed',
    label: 'Saira Extra Condensed',
    family: 'Saira Extra Condensed',
    fallback: 'sans-serif',
    file: `${LIB}/saira-extra-condensed.woff2`,
  },
  {
    key: 'sansation',
    label: 'Sansation',
    family: 'Sansation',
    fallback: 'sans-serif',
    file: `${LIB}/sansation.woff2`,
  },
  {
    key: 'share',
    label: 'Share',
    family: 'Share',
    fallback: 'sans-serif',
    file: `${LIB}/share.woff2`,
  },
  {
    key: 'sofia',
    label: 'Sofia',
    family: 'Sofia',
    fallback: 'cursive',
    file: `${LIB}/sofia.woff2`,
  },
  {
    key: 'warnes',
    label: 'Warnes',
    family: 'Warnes',
    fallback: 'sans-serif',
    file: `${LIB}/warnes.woff2`,
  },
  {
    key: 'yanone-kaffeesatz',
    label: 'Yanone Kaffeesatz',
    family: 'Yanone Kaffeesatz',
    fallback: 'sans-serif',
    file: `${LIB}/yanone-kaffeesatz.woff2`,
  },
  {
    key: 'zen-dots',
    label: 'Zen Dots',
    family: 'Zen Dots',
    fallback: 'sans-serif',
    file: `${LIB}/zen-dots.woff2`,
  },
];

/**
 * The UI body font — what the whole interface is set in (Settings → Appearance).
 *
 * Separate list from DISPLAY_FONTS because the job is different: those are
 * decorative faces for two words of wordmark, these have to stay legible in a
 * 13px table cell at 400 and a button at 600. They share the pipeline, though —
 * same `@font-face` emitter, same lazy loading, same var-override mechanism.
 *
 * `inter` is the default and carries no file: it is the always-loaded next/font
 * face (lib/fonts.ts), which is right for the font every page paints. The rest
 * are opt-in and fetched only when actually selected.
 */
export const DEFAULT_UI_FONT = 'inter';

export const UI_FONTS: DisplayFont[] = [
  {
    key: 'inter',
    label: 'Inter',
    family: null,
    fallback: 'sans-serif',
    file: null,
    category: 'sans',
  },
  // ── sans ──────────────────────────────────────────────────────────────────
  {
    key: 'geist',
    label: 'Geist',
    family: 'Geist',
    fallback: 'sans-serif',
    file: `${LIB}/geist.woff2`,
    weight: VARIABLE,
    category: 'sans',
  },
  {
    key: 'plus-jakarta-sans',
    label: 'Plus Jakarta Sans',
    family: 'Plus Jakarta Sans',
    fallback: 'sans-serif',
    file: `${LIB}/plus-jakarta-sans.woff2`,
    weight: VARIABLE,
    category: 'sans',
  },
  {
    key: 'manrope',
    label: 'Manrope',
    family: 'Manrope',
    fallback: 'sans-serif',
    file: `${LIB}/manrope.woff2`,
    weight: VARIABLE,
    category: 'sans',
  },
  {
    key: 'figtree',
    label: 'Figtree',
    family: 'Figtree',
    fallback: 'sans-serif',
    file: `${LIB}/figtree.woff2`,
    weight: VARIABLE,
    category: 'sans',
  },
  {
    key: 'ibm-plex-sans',
    label: 'IBM Plex Sans',
    family: 'IBM Plex Sans',
    fallback: 'sans-serif',
    file: `${LIB}/ibm-plex-sans.woff2`,
    weight: VARIABLE,
    category: 'sans',
  },
  // Designed by the Braille Institute for low-vision readability: every glyph
  // is drawn to be unmistakable for another (1/l/I, 0/O, rn/m). The one face
  // here chosen for legibility rather than looks — it pairs with the size
  // control, which is the other half of the same accessibility answer.
  {
    key: 'atkinson-hyperlegible',
    label: 'Atkinson Hyperlegible',
    family: 'Atkinson Hyperlegible Next',
    fallback: 'sans-serif',
    file: `${LIB}/atkinson-hyperlegible.woff2`,
    weight: VARIABLE,
    category: 'sans',
  },
  // ── mono ──────────────────────────────────────────────────────────────────
  {
    key: 'jetbrains-mono',
    label: 'JetBrains Mono',
    family: 'JetBrains Mono',
    fallback: 'monospace',
    file: `${LIB}/jetbrains-mono.woff2`,
    weight: VARIABLE,
    category: 'mono',
  },
  {
    key: 'geist-mono',
    label: 'Geist Mono',
    family: 'Geist Mono',
    fallback: 'monospace',
    file: `${LIB}/geist-mono.woff2`,
    weight: VARIABLE,
    category: 'mono',
  },
  // ── character ─────────────────────────────────────────────────────────────
  // Fraunces ships a literal WONK axis; Bricolage and Space Grotesk are the
  // quiet-but-odd end. Legible enough to live in, strange enough to be a choice.
  {
    key: 'fraunces',
    label: 'Fraunces',
    family: 'Fraunces',
    fallback: 'serif',
    file: `${LIB}/fraunces.woff2`,
    weight: VARIABLE,
    category: 'character',
  },
  {
    key: 'bricolage-grotesque',
    label: 'Bricolage Grotesque',
    family: 'Bricolage Grotesque',
    fallback: 'sans-serif',
    file: `${LIB}/bricolage-grotesque.woff2`,
    weight: VARIABLE,
    category: 'character',
  },
  {
    key: 'space-grotesk',
    label: 'Space Grotesk',
    family: 'Space Grotesk',
    fallback: 'sans-serif',
    file: `${LIB}/space-grotesk.woff2`,
    weight: VARIABLE,
    category: 'character',
  },
];

/** UI font size. Scales the ROOT font-size, and because the shell is rem-based
 *  (h-16 header, rem paddings) the whole interface scales with it rather than
 *  just the letters — the same thing OS display scaling does. */
export type UiFontSize = 'small' | 'medium' | 'large';
export const UI_FONT_SIZES: Array<{ id: UiFontSize; label: string; hint: string }> = [
  { id: 'small', label: 'Small', hint: 'Denser — more on screen' },
  { id: 'medium', label: 'Medium', hint: 'Default' },
  { id: 'large', label: 'Large', hint: 'Roomier — easier to read' },
];
export const DEFAULT_UI_FONT_SIZE: UiFontSize = 'medium';

export function resolveUiFontSize(v: string | null | undefined): UiFontSize {
  return v === 'small' || v === 'large' || v === 'medium' ? v : DEFAULT_UI_FONT_SIZE;
}

// Both lists share one lookup: keys are unique across them (asserted in
// display-fonts.test.ts), so a stored key resolves wherever it came from.
const BY_KEY = new Map([...DISPLAY_FONTS, ...UI_FONTS].map((f) => [f.key, f]));

export function fontByKey(key: string | null | undefined): DisplayFont | undefined {
  return key ? BY_KEY.get(key) : undefined;
}

/**
 * CSS `font-family` value for a font key — what the wordmark/title elements
 * resolve to. `sans` maps to the app UI font var; everything else is its
 * declared family + generic fallback. Unknown keys → null (caller keeps default).
 */
export function fontFamilyValue(key: string | null | undefined): string | null {
  const f = fontByKey(key);
  if (!f) return null;
  if (f.key === 'sans') return 'var(--font-sans, ui-sans-serif, sans-serif)';
  if (!f.family) return null;
  return `"${f.family}", ${f.fallback}`;
}

/**
 * `@font-face` rules for every library face — display AND UI — injected once
 * server-side in the root layout so the declarations are present on first paint
 * (no FOUT wait) yet the files stay lazily fetched. Deterministic (no runtime
 * state) so it's safe to render into a <style>.
 */
export function displayFontFaceCss(): string {
  return [...DISPLAY_FONTS, ...UI_FONTS]
    .filter((f) => f.file && f.family)
    .map(
      (f) =>
        `@font-face{font-family:"${f.family}";src:url("${f.file}") format("${fileFormat(f.file!)}");font-display:swap;font-style:normal;${f.weight ? `font-weight:${f.weight};` : ''}}`,
    )
    .join('\n');
}

/** `format()` hint for a face file. A wrong hint makes the browser skip the
 *  face entirely, so it is derived from the filename, never assumed. */
function fileFormat(file: string): string {
  if (file.endsWith('.woff2')) return 'woff2';
  if (file.endsWith('.woff')) return 'woff';
  if (file.endsWith('.otf')) return 'opentype';
  return 'truetype';
}

/**
 * Resolve the two stored display-font keys to their CSS `font-family` values,
 * dropping defaults and unknown keys — the shared projection behind the
 * server-rendered `<html>` appearance attributes (see appearance.ts). Values
 * land as inline style on the root element; "default" is the absence of the
 * var, so the elements' var() fallbacks win. There is deliberately NO
 * localStorage / before-paint-script path anymore: the document arrives
 * correct, and the client providers read the rendered attributes back as
 * their initial state.
 */
export type ResolvedFontVars = { wordmark?: string; pageTitle?: string; ui?: string };
export function resolveFontVars(
  logo: string | null | undefined,
  title: string | null | undefined,
  ui?: string | null | undefined,
): ResolvedFontVars {
  const out: ResolvedFontVars = {};
  if (logo && logo !== DEFAULT_LOGO_FONT) {
    const v = fontFamilyValue(logo);
    if (v) out.wordmark = v;
  }
  if (title && title !== DEFAULT_TITLE_FONT) {
    const v = fontFamilyValue(title);
    if (v) out.pageTitle = v;
  }
  // The UI font overrides `--font-sans` itself rather than introducing a var of
  // its own, so everything that already resolves it — the `font-sans` utility
  // and every element inheriting from the root — follows the choice with no
  // further wiring. Custom properties inherit, so setting it once at the root
  // is the whole mechanism.
  if (ui && ui !== DEFAULT_UI_FONT) {
    const v = fontFamilyValue(ui);
    if (v) out.ui = v;
  }
  return out;
}
