/**
 * Display-font registry — the SINGLE source of truth for the user-selectable
 * wordmark + page-title fonts (Settings → Appearance → Fonts).
 *
 * One list drives everything: the `@font-face` block (generated by
 * `displayFontFaceCss`, injected once in the root layout), the two pickers, and
 * the runtime CSS-var override in `FontProvider`. Add a font in ONE place —
 * drop the file in `public/fonts/library/<key>.ttf` and add a row here.
 *
 * Loading is lazy by construction: a browser fetches a font file only when it
 * actually paints text in that family, so declaring ~25 `@font-face` rules costs
 * nothing until a font is *selected* (or previewed while the picker is open) —
 * the runtime cost is the two chosen faces, not the whole library. This is why
 * we can ship variety without eager-bundling every face (unlike `next/font`,
 * which is right for the always-loaded UI font but wrong for an opt-in library).
 *
 * `sans` and `bukhari` are the two defaults and carry no library file: `sans`
 * resolves to the app UI font (`--font-sans`), `bukhari` to the existing
 * next/font wordmark face.
 */

export type FontFallback = 'sans-serif' | 'serif' | 'cursive' | 'monospace';

export type DisplayFont = {
  /** Stable slug stored in preferences + used as the file basename. */
  key: string;
  /** Human label shown in the picker. */
  label: string;
  /** CSS `font-family` name declared by our `@font-face` (or null for the two
   *  built-in defaults, which map to existing families). */
  family: string | null;
  /** Generic fallback appended after the family. */
  fallback: FontFallback;
  /** Public path to the face file, or null for the built-in defaults. */
  file: string | null;
};

/** Default wordmark = the existing Bukhari face; default title = the UI sans. */
export const DEFAULT_LOGO_FONT = 'bukhari';
export const DEFAULT_TITLE_FONT = 'sans';

/** localStorage keys — the before-paint cache (mirrors the colour theme). */
export const FONT_LOGO_STORAGE_KEY = 'mantle_font_logo';
export const FONT_TITLE_STORAGE_KEY = 'mantle_font_title';

const LIB = '/fonts/library';

export const DISPLAY_FONTS: DisplayFont[] = [
  // Built-in defaults (no library file).
  { key: 'sans', label: 'System (Inter)', family: null, fallback: 'sans-serif', file: null },
  {
    key: 'bukhari',
    label: 'Bukhari Script',
    family: 'Bukhari Script',
    fallback: 'cursive',
    file: '/fonts/BukhariScript-Regular.ttf',
  },
  // Library — one representative face per family (self-hosted, OFL; licenses in
  // public/fonts/library/licenses/).
  { key: 'allison', label: 'Allison', family: 'Allison', fallback: 'cursive', file: `${LIB}/allison.ttf` },
  { key: 'arizonia', label: 'Arizonia', family: 'Arizonia', fallback: 'cursive', file: `${LIB}/arizonia.ttf` },
  { key: 'biorhyme', label: 'BioRhyme', family: 'BioRhyme', fallback: 'serif', file: `${LIB}/biorhyme.ttf` },
  { key: 'bitcount', label: 'Bitcount', family: 'Bitcount Prop Double', fallback: 'monospace', file: `${LIB}/bitcount.ttf` },
  { key: 'bungee-shade', label: 'Bungee Shade', family: 'Bungee Shade', fallback: 'sans-serif', file: `${LIB}/bungee-shade.ttf` },
  { key: 'capriola', label: 'Capriola', family: 'Capriola', fallback: 'sans-serif', file: `${LIB}/capriola.ttf` },
  { key: 'cinzel-decorative', label: 'Cinzel Decorative', family: 'Cinzel Decorative', fallback: 'serif', file: `${LIB}/cinzel-decorative.ttf` },
  { key: 'economica', label: 'Economica', family: 'Economica', fallback: 'sans-serif', file: `${LIB}/economica.ttf` },
  { key: 'fugaz-one', label: 'Fugaz One', family: 'Fugaz One', fallback: 'sans-serif', file: `${LIB}/fugaz-one.ttf` },
  { key: 'jersey-15', label: 'Jersey 15', family: 'Jersey 15', fallback: 'sans-serif', file: `${LIB}/jersey-15.ttf` },
  { key: 'la-belle-aurore', label: 'La Belle Aurore', family: 'La Belle Aurore', fallback: 'cursive', file: `${LIB}/la-belle-aurore.ttf` },
  { key: 'londrina-outline', label: 'Londrina Outline', family: 'Londrina Outline', fallback: 'sans-serif', file: `${LIB}/londrina-outline.ttf` },
  { key: 'montez', label: 'Montez', family: 'Montez', fallback: 'cursive', file: `${LIB}/montez.ttf` },
  { key: 'nabla', label: 'Nabla', family: 'Nabla', fallback: 'sans-serif', file: `${LIB}/nabla.ttf` },
  { key: 'playball', label: 'Playball', family: 'Playball', fallback: 'cursive', file: `${LIB}/playball.ttf` },
  { key: 'playwrite-ie', label: 'Playwrite IE', family: 'Playwrite IE', fallback: 'cursive', file: `${LIB}/playwrite-ie.ttf` },
  { key: 'podkova', label: 'Podkova', family: 'Podkova', fallback: 'serif', file: `${LIB}/podkova.ttf` },
  { key: 'saira-extra-condensed', label: 'Saira Extra Condensed', family: 'Saira Extra Condensed', fallback: 'sans-serif', file: `${LIB}/saira-extra-condensed.ttf` },
  { key: 'sansation', label: 'Sansation', family: 'Sansation', fallback: 'sans-serif', file: `${LIB}/sansation.ttf` },
  { key: 'share', label: 'Share', family: 'Share', fallback: 'sans-serif', file: `${LIB}/share.ttf` },
  { key: 'sofia', label: 'Sofia', family: 'Sofia', fallback: 'cursive', file: `${LIB}/sofia.ttf` },
  { key: 'square-peg', label: 'Square Peg', family: 'Square Peg', fallback: 'cursive', file: `${LIB}/square-peg.ttf` },
  { key: 'warnes', label: 'Warnes', family: 'Warnes', fallback: 'sans-serif', file: `${LIB}/warnes.ttf` },
  { key: 'yanone-kaffeesatz', label: 'Yanone Kaffeesatz', family: 'Yanone Kaffeesatz', fallback: 'sans-serif', file: `${LIB}/yanone-kaffeesatz.ttf` },
  { key: 'zen-dots', label: 'Zen Dots', family: 'Zen Dots', fallback: 'sans-serif', file: `${LIB}/zen-dots.ttf` },
];

const BY_KEY = new Map(DISPLAY_FONTS.map((f) => [f.key, f]));

export function fontByKey(key: string | null | undefined): DisplayFont | undefined {
  return key ? BY_KEY.get(key) : undefined;
}

/**
 * CSS `font-family` value for a font key — what the wordmark/title elements
 * resolve to. `sans` maps to the app UI font var; everything else is its
 * declared family + generic fallback. Unknown keys → null (caller keeps default).
 */
export function fontFamilyValue(key: string | null | undefined): string | null {
  const f = fontByKey(key);
  if (!f) return null;
  if (f.key === 'sans') return 'var(--font-sans, ui-sans-serif, sans-serif)';
  if (!f.family) return null;
  return `"${f.family}", ${f.fallback}`;
}

/**
 * `@font-face` rules for every library face — injected once server-side in the
 * root layout so the declarations are present on first paint (no FOUT wait) yet
 * the files stay lazily fetched. Deterministic (no runtime state) so it's safe
 * to render into a <style>.
 */
export function displayFontFaceCss(): string {
  return DISPLAY_FONTS.filter((f) => f.file && f.family)
    .map(
      (f) =>
        `@font-face{font-family:"${f.family}";src:url("${f.file}") format("truetype");font-display:swap;font-style:normal;}`,
    )
    .join('\n');
}

/**
 * Before-paint script (mirrors the colour-theme one in the root layout): reads
 * this browser's cached choices from localStorage and sets the two CSS vars
 * BEFORE React hydrates, so a stored custom font paints without a flash of the
 * default. A default choice sets nothing (the element's var() fallback wins).
 */
export function fontPrepaintScript(): string {
  const map: Record<string, string> = {};
  for (const f of DISPLAY_FONTS) {
    const v = fontFamilyValue(f.key);
    if (v) map[f.key] = v;
  }
  return (
    `(function(){try{var M=${JSON.stringify(map)},` +
    `L=localStorage.getItem('${FONT_LOGO_STORAGE_KEY}'),` +
    `T=localStorage.getItem('${FONT_TITLE_STORAGE_KEY}'),r=document.documentElement.style;` +
    `if(L&&L!=='${DEFAULT_LOGO_FONT}'&&M[L])r.setProperty('--font-wordmark',M[L]);` +
    `if(T&&T!=='${DEFAULT_TITLE_FONT}'&&M[T])r.setProperty('--font-page-title',M[T]);` +
    `}catch(e){}})();`
  );
}
