import { NextResponse } from '@/server/http-compat';
import { asc, eq } from 'drizzle-orm';
import { db, curatedModels } from '@mantle/db';
import { getOwnerOr401 } from '@/lib/auth';
import { MODEL_POOLS } from '@/lib/model-pools';

/**
 * Export the curated pools as the repo-shipped TS module. The curator drafts
 * in the DB (this brain); the durable template is a dependency-free module in
 * packages/client-types (house style — model-choices.ts, display-fonts.ts).
 * This route generates that file's content so a session can paste/commit it.
 */
export async function GET() {
  const user = await getOwnerOr401();
  if (user instanceof Response) return user;
  const entries = await db
    .select()
    .from(curatedModels)
    .where(eq(curatedModels.ownerId, user.id))
    .orderBy(asc(curatedModels.pool), asc(curatedModels.position), asc(curatedModels.createdAt));

  const byPool = MODEL_POOLS.map((p) => ({
    pool: p.id,
    label: p.label,
    models: entries
      .filter((e) => e.pool === p.id)
      .map((e) => ({
        name: e.name,
        vendor: e.vendor,
        routes: e.routes,
        pricing: e.pricing,
        rating: e.rating,
        note: e.note,
      })),
  })).filter((p) => p.models.length > 0);

  const header =
    '// GENERATED by /api/model-pools/export — curated model pools.\n' +
    `// Exported ${new Date().toISOString()} from a live curator. Do not hand-edit\n` +
    '// entries here; curate in /models and re-export.\n\n' +
    'export const CURATED_MODEL_POOLS = ';
  const ts = `${header}${JSON.stringify(byPool, null, 2)} as const;\n`;

  return NextResponse.json({ pools: byPool, ts });
}
