/* GENERATED FILE — do not edit. `pnpm themes:build` regenerates it from
 * themes/seeds.mjs. Swatches are [primary, accent, background] of the
 * generated light mode, so the picker preview can never desync from the CSS. */
import type { ColorTheme } from './themes';

export const GENERATED_COLOR_THEMES: ColorTheme[] = [
  { id: 'clean-slate', label: 'Clean Slate', swatches: ['#6264ef', '#e0e7ff', '#f8fafc'] },
  { id: 'amber-minimal', label: 'Amber Minimal', swatches: ['#f59e0b', '#fffbeb', '#ffffff'] },
  { id: 'amethyst-haze', label: 'Amethyst Haze', swatches: ['#7e6d9e', '#e6a5b8', '#f8f7fa'] },
  { id: 'bold-tech', label: 'Bold Tech', swatches: ['#8757f1', '#dbeafe', '#ffffff'] },
  { id: 'bubblegum', label: 'Bubblegum', swatches: ['#c64590', '#fbe2a7', '#f6e6ee'] },
  { id: 'caffeine', label: 'Caffeine', swatches: ['#644a40', '#e8e8e8', '#f9f9f9'] },
  { id: 'candyland', label: 'Candyland', swatches: ['#ffc0cb', '#ffff00', '#f7f9fa'] },
  { id: 'catppuccin', label: 'Catppuccin', swatches: ['#8839ef', '#007dbb', '#eff1f5'] },
  { id: 'claude', label: 'Claude', swatches: ['#bd5937', '#e9e6dc', '#faf9f5'] },
  { id: 'claymorphism', label: 'Claymorphism', swatches: ['#6264ef', '#f3e5f5', '#e7e5e4'] },
  { id: 'cosmic-night', label: 'Cosmic Night', swatches: ['#6e56cf', '#d8e6ff', '#f5f5ff'] },
  { id: 'cyberpunk', label: 'Cyberpunk', swatches: ['#dc00a9', '#00ffcc', '#f8f9fa'] },
  { id: 'darkmatter', label: 'Darkmatter', swatches: ['#b85c23', '#eeeeee', '#ffffff'] },
  { id: 'doom-64', label: 'Doom 64', swatches: ['#b71c1c', '#3f7bad', '#cccccc'] },
  { id: 'elegant-luxury', label: 'Elegant Luxury', swatches: ['#9b2c2c', '#fef3c7', '#faf7f5'] },
  { id: 'graphite', label: 'Graphite', swatches: ['#606060', '#c0c0c0', '#f0f0f0'] },
  { id: 'kodama-grove', label: 'Kodama Grove', swatches: ['#6d7c2d', '#dbc894', '#e4d7b0'] },
  { id: 'midnight-bloom', label: 'Midnight Bloom', swatches: ['#6c5ce7', '#727a4f', '#f9f9f9'] },
  { id: 'mocha-mousse', label: 'Mocha Mousse', swatches: ['#966b59', '#e4c7b8', '#f1f0e5'] },
  { id: 'modern-minimal', label: 'Modern Minimal', swatches: ['#2b72e5', '#e0f2fe', '#ffffff'] },
  { id: 'mono', label: 'Mono', swatches: ['#737373', '#f5f5f5', '#ffffff'] },
  { id: 'nature', label: 'Nature', swatches: ['#2e7d32', '#c8e6c9', '#f8f5f0'] },
  { id: 'neo-brutalism', label: 'Neo Brutalism', swatches: ['#ea101f', '#0066ff', '#ffffff'] },
  { id: 'notebook', label: 'Notebook', swatches: ['#606060', '#f3eac8', '#f9f9f9'] },
  { id: 'ocean-breeze', label: 'Ocean Breeze', swatches: ['#008a22', '#d1fae5', '#f0f8ff'] },
  { id: 'pastel-dreams', label: 'Pastel Dreams', swatches: ['#8063ce', '#f3e5f5', '#f7f3f9'] },
  { id: 'perpetuity', label: 'Perpetuity', swatches: ['#01838c', '#c9e5e7', '#e8f0f0'] },
  { id: 'pinnacle', label: 'Pinnacle', swatches: ['#457928', '#e9f1d6', '#f7faf7'] },
  { id: 'quantum-rose', label: 'Quantum Rose', swatches: ['#e40079', '#ffc1e3', '#fff0f8'] },
  { id: 'sage-garden', label: 'Sage Garden', swatches: ['#687b6e', '#bfc9bb', '#f8f7f4'] },
  { id: 'soft-pop', label: 'Soft Pop', swatches: ['#4f46e5', '#f59e0b', '#f7f9f3'] },
  { id: 'solar-dusk', label: 'Solar Dusk', swatches: ['#b45309', '#f2daba', '#fdfbf7'] },
  { id: 'starry-night', label: 'Starry Night', swatches: ['#3a5ba0', '#467a96', '#f5f7fa'] },
  { id: 'sunset-horizon', label: 'Sunset Horizon', swatches: ['#ca4e31', '#feb47b', '#fff9f5'] },
  { id: 'supabase', label: 'Supabase', swatches: ['#72e3ad', '#ededed', '#fcfcfc'] },
  { id: 't3-chat', label: 'T3 Chat', swatches: ['#a84370', '#f1c4e6', '#faf5fa'] },
  { id: 'tangerine', label: 'Tangerine', swatches: ['#cd4b25', '#d6e4f0', '#e8ebed'] },
  { id: 'twitter', label: 'Twitter', swatches: ['#007acc', '#e3ecf6', '#ffffff'] },
  { id: 'vercel', label: 'Vercel', swatches: ['#000000', '#ebebeb', '#fcfcfc'] },
  { id: 'vintage-paper', label: 'Vintage Paper', swatches: ['#966d44', '#d4c8aa', '#f5f1e6'] },
  { id: 'violet-bloom', label: 'Violet Bloom', swatches: ['#7033ff', '#e2ebff', '#fdfdfd'] },
];
