// PAGES: six, written to show what a page can hold. Images from Files
// (`media:gen:`), page link cards (`page:gen:`), mentions of other items
// (`mention:node:gen:`), callouts, columns, tables, to-do lists, a foldable
// heading and one formula in math. The seeder swaps every `gen:<id>` for the
// real id once that item exists, so a page may only point at items created
// before it (the test checks the order).
//
// Levels: two team pages, the procedure revision family for the client
// (rev A superseded by rev B), one private page and one public page.
// Images always come from the same tier's Files folder; mentions may point
// at anything the page's readers can also read (a team page may mention a
// client item; a client page mentions client items only).

export function generate() {
  const nodes = [];
  const page = (id, tier, offset, title, tags, body) =>
    nodes.push({ id, kind: 'page', tier, title, body: body.join('\n'), offset, tags, meta: {} });

  // ── Client: the procedure revision family ─────────────────────────────────
  page('page-procedure-rev-a', 'client', -60, 'PS3 changeover procedure, rev A', ['pumphouse', 'procedure', 'rev-a'], [
    '# PS3 changeover procedure, rev A',
    '',
    ':::warning',
    '**Superseded.** Rev B replaced this revision three weeks later. Kept for the record; do not work to it.',
    ':::',
    '',
    'Moves Pump Station 3 from the old telemetry outstation to the new RTU without losing sight of the station from the Meridian control room for more than one shift.',
    '',
    '## Steps',
    '',
    '1. Confirm the commissioning window with the control room in writing.',
    '2. Wire the new RTU in parallel with the old one. The old one keeps reporting.',
    '3. Loop check every signal: pressure first, then flow, then level.',
    '4. Hand the station to the new RTU at hold point H3. Park the old one, still wired.',
    '',
    '## Open questions at issue',
    '',
    '- What should the delivery valve do if the radio link drops mid-changeover?',
  ]);

  page('page-procedure-rev-b', 'client', -21, 'PS3 changeover procedure, rev B', ['pumphouse', 'procedure', 'rev-b', 'current'], [
    '# PS3 changeover procedure, rev B',
    '',
    ':::success',
    '**Issued for use.** Supersedes [PS3 changeover procedure, rev A](mention:node:gen:page-procedure-rev-a). Approved by Gordon Bekker, plant superintendent. Loop checks witnessed by Lena Marsh.',
    ':::',
    '',
    '![PS3 from the access road](media:gen:img-ps3-station)',
    '',
    '## What changed from rev A',
    '',
    ':::columns',
    '### Loop check order',
    'Level first, then flow, then pressure. Rev A had pressure first, which would have run a pump on a level signal nobody had proven. Lena Marsh caught it in review.',
    '+++',
    '### Delivery valve on comms loss',
    'XV-401 now **holds its last position** when the radio link drops. That is the answer to TQ-004, written into the procedure so nobody has to remember it.',
    ':::',
    '',
    '## Hold points',
    '',
    '| Hold point | When | Signed by |',
    '| --- | --- | --- |',
    '| H1 | Before the old RTU is isolated | Gordon Bekker |',
    '| H2 | After the level loop LT-101 is proven | Lena Marsh (witness) |',
    '| H3 | Before the control room takes the station | Gordon Bekker |',
    '',
    '## Steps {fold}',
    '',
    '1. Confirm the five-day commissioning window with the control room, in writing, the week before.',
    '2. Check the calibrator certificate is in date for the whole window.',
    '3. Wire the new RTU in parallel. The old RTU keeps reporting until H3.',
    '4. Sign **H1**, then isolate the old RTU outputs only. Its inputs stay live.',
    '5. Loop check in the rev B order: LT-101, FT-201, PT-301, then the XV-401 fail-safe test.',
    '6. Sign **H2** once the level loop reads the same at the sensor and on the control room screen.',
    '7. Pull the radio link for sixty seconds and confirm XV-401 holds position.',
    '8. Sign **H3**. The control room takes the station on the new RTU.',
    '',
    '![PS3 radio mast, after the extension](media:gen:img-ps3-radio-mast)',
    '',
    '## Back-out',
    '',
    ':::warning',
    'If H3 is not signed by the end of the window, reconnect the old RTU outputs and return the station to the old telemetry. Nothing in this procedure removes the old RTU until H3 is signed.',
    ':::',
    '',
    '## Reference',
    '',
    '- Drawing: [PS3 telemetry after the changeover](mention:node:gen:draw-ps3-telemetry)',
    '- Snags found during the checks: [PS3 snag list](mention:node:gen:tbl-snag-list)',
    '- Signal ranges: [PS3 I/O schedule, rev B](media:gen:doc-io-schedule)',
    '',
    '![Delivery valve chamber](media:gen:img-ps3-valve-chamber)',
  ]);

  // ── Team ──────────────────────────────────────────────────────────────────
  page('page-standby-findings', 'team', -6, 'Standby power study: draft findings', ['island', 'findings', 'draft'], [
    '# Standby power study: draft findings',
    '',
    ':::info',
    '**Draft for internal review.** The findings review with Gordon Bekker is in two weeks. Rowan owns this page; comments inline, please.',
    ':::',
    '',
    '![The diesel that did not start](media:gen:img-ps3-standby-generator)',
    '',
    '## The question',
    '',
    'On the storm night the grid went down, the PS3 diesel did not start, and the station stood for three hours. Meridian asked us: can PS3 ride through a **four-hour grid outage** without the diesel?',
    '',
    '## The load',
    '',
    'From the [PS3 load profile, typical winter day](mention:node:gen:tbl-load-profile): one pump is 65 kW, two pumps are 124 kW, idle is 4 kW. During an outage Meridian runs one pump and lets the hilltop reservoir carry the rest, so the design load is **65 kW**, and the design case is night, with no solar.',
    '',
    '## Three options',
    '',
    '| Option | What it is | Night autonomy, one pump | Verdict |',
    '| --- | --- | --- | --- |',
    '| A | New diesel, same shed | Fuel-limited, not battery | Fixes the symptom, keeps the risk |',
    '| B | 60 kWp solar canopy and a 350 kWh battery | 4.6 h | ==Recommended== |',
    '| C | 400 kWh battery, no solar | 5.3 h | Works, costs more, no daily saving |',
    '',
    '![Option B: solar canopy on the yard](media:gen:img-island-solar-canopy)',
    '',
    ':::columns',
    '![Option B: battery container and transformer](media:gen:img-island-battery-container)',
    '+++',
    '![Main board with the transfer switch](media:gen:img-island-switchboard)',
    ':::',
    '',
    '## How the autonomy is worked out',
    '',
    'Usable energy over the net load:',
    '',
    '$$t_{auto} = \\frac{E_{nom} \\cdot DoD \\cdot \\eta_{inv}}{P_{load} - P_{pv}}$$',
    '',
    'For option B that is 350 kWh at 90 % depth and 95 % inverter efficiency, so 299 kWh over 65 kW: **4.6 hours**. The live version, with the rating scale, is the [Battery autonomy for a grid outage](mention:node:gen:formula-battery-autonomy) formula. The 300 kWh container would give 3.95 h, which is short.',
    '',
    '## Before the review',
    '',
    '- [x] Load profile from Lena\'s logger data',
    '- [x] Autonomy for all three options',
    '- [ ] Storage sizing section, with the cell ageing allowance',
    '- [ ] Send the draft to Gordon a week ahead',
    '',
    'The scheme drawing: [Standby scheme, option B](mention:node:gen:draw-standby-option-b).',
  ]);

  page('page-ps3-brief', 'team', -5, 'PS3 telemetry retrofit: project brief', ['pumphouse', 'brief'], [
    '# PS3 telemetry retrofit: project brief',
    '',
    ':::warning',
    '**The commissioning window opens in a week.** Five days, agreed in writing with Gordon Bekker. Loop checks day 2 comes first.',
    ':::',
    '',
    'Pump Station 3 lifts water from the valley main to the hilltop reservoir for Meridian Waterworks. Its telemetry outstation is twenty years old and drops out in wet weather. We replace it with a new RTU, extend the radio mast, prove every signal, and hand the station back to the control room without a blind shift.',
    '',
    '![PS3 pump hall](media:gen:img-ps3-pump-hall)',
    '',
    '## Who',
    '',
    '| Person | Role on this job |',
    '| --- | --- |',
    '| Alex Carter | Lead, client contact |',
    '| Tessa Okafor | RTU, radio link, loop checks |',
    '| Rowan Mercer | Pumps; also leads the standby power study at the same station |',
    '| Gordon Bekker (Meridian) | Approves every procedure revision, signs hold points |',
    '| Lena Marsh (Meridian) | SCADA technician, witnesses the loop checks |',
    '',
    '## Where we are',
    '',
    ':::columns',
    '### Done',
    '- Rev A issued, then superseded',
    '- TQ-004 answered (valve holds position)',
    '- Rev B approved and issued',
    '- Loop checks day 1: 7 of 12 signals',
    '+++',
    '### Next',
    '- Loop checks day 2, witnessed by Lena',
    '- Close the open snags before the window',
    '- Commissioning window, then hold point H3',
    ':::',
    '',
    '![New RTU cabinet, as delivered](media:gen:img-ps3-rtu-cabinet)',
    '',
    '## Where things live',
    '',
    '- The procedure we work to: [PS3 changeover procedure, rev B](mention:node:gen:page-procedure-rev-b)',
    '- Signals and what is checked: [PS3 I/O schedule](mention:node:gen:tbl-io-schedule)',
    '- What is still open: [PS3 snag list](mention:node:gen:tbl-snag-list)',
    '- The running cost side: [Pump station specific energy and duty cost](mention:node:gen:formula-pump-specific-energy)',
    '',
    'The standby power study runs at the same station:',
    '',
    '[Standby power study: draft findings](page:gen:page-standby-findings)',
  ]);

  // ── Private ───────────────────────────────────────────────────────────────
  page('page-why-battery', 'private', -14, 'Why I want option B to win', ['island', 'thinking'], [
    '# Why I want option B to win',
    '',
    '*Private. Not for Gordon yet, and maybe never in this form.*',
    '',
    '![Storm night at PS3](media:gen:img-island-storm-night)',
    '',
    'The storm night was not a diesel problem. It was a **testing** problem: the generator had passed its monthly run on a dry afternoon and failed on the one wet night that mattered. A new diesel buys the same risk with a newer paint job.',
    '',
    'A battery is exercised every day if it also shaves the morning peak. A thing that works every day is a thing you trust on the night.',
    '',
    '## What would change my mind',
    '',
    '- If Meridian cannot run on one pump for four hours (ask Gordon about reservoir level in January).',
    '- If the 350 kWh price moves more than 15 % before the review.',
    '- If Rowan\'s ageing allowance pushes us to the 400 kWh container.',
    '',
    'Numbers to keep honest: [Battery options compared](mention:node:gen:tbl-battery-options) and the [Project budget](mention:node:gen:tbl-budget). The findings draft is [Standby power study: draft findings](mention:node:gen:page-standby-findings).',
  ]);

  // ── Public ────────────────────────────────────────────────────────────────
  page('page-who-we-are', 'public', -88, 'Harbour Labs: who we are', ['studio', 'public'], [
    '# Harbour Labs: who we are',
    '',
    '![The Harbour Labs studio](media:gen:img-harbour-labs-studio)',
    '',
    'Harbour Labs is a three-person engineering studio. We put telemetry, controls and standby power into water infrastructure, and we write the procedures that let a utility change a live station without losing sight of it.',
    '',
    '## How we work',
    '',
    '- **Procedures are revisions.** We never edit an issued procedure; we issue the next revision and say what changed.',
    '- **Every signal is proven.** A loop check injects a known value at the sensor and reads it on the operator\'s screen.',
    '- **Nothing is removed until the hold point is signed.** The old kit stays wired until the client says so.',
    '',
    '![A letter for the control room](media:gen:img-jackdaw-letter)',
    '',
    'How a reading travels, in one picture: [How a reading reaches the control room](mention:node:gen:draw-reading-path).',
  ]);

  return { nodes };
}
