/**
 * Seed the member chat: a team member asks the brain real questions, and the
 * brain answers them for real.
 *
 * This replaces seed-forum.ts. The Team Forum was retired on main (migration
 * 0177 drops its tables; every /api/team/forum route is gone), and the surface
 * where the brain does visible work for the team is now the member chat: a
 * member login talks to the `team-responder` agent, and the admin reads the
 * thread under Team. The answers are GENERATED by an actual agent turn, never
 * written by hand: a demo whose pitch is "watch the brain work" cannot fake
 * the working.
 *
 * REQUIREMENTS, all of which fail loudly instead of leaving an empty thread:
 *   - a WRITABLE server/web (the serve-time reader cannot post)
 *   - server/api running: the turn is a workflow on the member queue, and
 *     without that process the question is stored and no answer ever arrives
 *   - a real chat key on the brain (seeded at onboarding), or the turn fails
 *   - enable-team.ts has run: it makes the member logins and opens the chat
 *     (`team-responder` at team level)
 *
 *   pnpm -C server/web exec tsx ../../demo/seed/seed-member-chat.ts
 */
import { memberPassword } from './lib/secrets.ts';

const SERVER = process.env.DEMO_SERVER_URL ?? 'http://127.0.0.1:3902';
// The member who asks: the controls engineer, one of the logins enable-team.ts
// makes (demo/world/world.json). Fictional, on a documentation domain.
const MEMBER_EMAIL = process.env.DEMO_CHAT_MEMBER_EMAIL ?? 'tessa@harbourlabs.example.com';
const MEMBER_PASSWORD = memberPassword();
/** Seconds to wait for each answer before giving up on it. */
const REPLY_WAIT_S = Number(process.env.DEMO_CHAT_REPLY_WAIT ?? 180);

/**
 * The one member question: the fifth of the demo's five real chats (the
 * other four are the owner's, demo/scripts/turns.sh). Answerable from what
 * the team can read (the Team and Client folders), so the answer shows
 * retrieval at the member's level and not the model's general knowledge.
 * It runs AFTER the drain, like every real turn: on an undrained brain an
 * agent loops and burns tokens for nothing.
 */
const QUESTIONS = [
  'I am on the PS3 commissioning window next week. What do I need to bring, and which open snags could stop us?',
];

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

let cookie = '';
async function api(path: string, init: RequestInit = {}) {
  const res = await fetch(`${SERVER}${path}`, {
    ...init,
    headers: { 'content-type': 'application/json', ...(cookie ? { cookie } : {}), ...(init.headers ?? {}) },
  });
  const sc = res.headers.getSetCookie?.() ?? [];
  if (sc.length) cookie = sc.map((c) => c.split(';')[0]).join('; ');
  return res;
}

type Message = { direction: 'inbound' | 'outbound'; text: string; status: 'pending' | 'complete' | 'failed' };
type Thread = { agent: { slug: string; name: string } | null; messages: Message[] };

async function thread(): Promise<Thread> {
  const res = await api('/api/member/chat');
  if (!res.ok) throw new Error(`GET /api/member/chat → ${res.status} ${(await res.text()).slice(0, 160)}`);
  return (await res.json()) as Thread;
}

/**
 * Answers that have LANDED: an outbound message that is complete and has text
 * in it. The reply row exists from the moment the question is asked (status
 * `pending`, empty), so counting messages would report success at once.
 */
const answersIn = (t: Thread) =>
  t.messages.filter((m) => m.direction === 'outbound' && m.status === 'complete' && m.text.trim().length > 0).length;
const failuresIn = (t: Thread) => t.messages.filter((m) => m.direction === 'outbound' && m.status === 'failed').length;

async function main() {
  const login = await api('/api/auth/login', {
    method: 'POST',
    body: JSON.stringify({ email: MEMBER_EMAIL, password: MEMBER_PASSWORD }),
  });
  if (!login.ok) {
    console.error(`✗ member login failed (${login.status}): run demo/seed/enable-team.ts first, it makes the member logins.`);
    process.exit(1);
  }
  const start = await thread();
  if (!start.agent) {
    console.error('✗ the member chat is not open: enable-team.ts sets the team-responder agent to team level.');
    process.exit(1);
  }

  const asked = new Set(start.messages.filter((m) => m.direction === 'inbound').map((m) => m.text.trim()));
  let unanswered = 0;
  for (const text of QUESTIONS) {
    if (asked.has(text)) {
      console.log(`· already asked: ${text.slice(0, 60)}`);
      continue;
    }
    const before = await thread();
    const have = answersIn(before);
    const failed = failuresIn(before);
    // 6 messages a minute per member. One question at a time, each waited
    // for, stays far inside that; a 429 is waited out, not treated as failure.
    let posted = false;
    for (let attempt = 0; attempt < 3 && !posted; attempt++) {
      const res = await api('/api/member/chat', { method: 'POST', body: JSON.stringify({ text }) });
      if (res.status === 429) {
        const wait = Number(res.headers.get('Retry-After') ?? 20);
        console.log(`  rate limited: waiting ${wait}s`);
        await sleep((wait + 1) * 1000);
        continue;
      }
      if (!res.ok) {
        console.error(`✗ the brain refused the question: ${res.status} ${(await res.text()).slice(0, 200)}`);
        process.exit(1);
      }
      posted = true;
    }
    if (!posted) {
      console.error('✗ still rate limited after three tries');
      process.exit(1);
    }
    console.log(`· asked: ${text.slice(0, 70)}`);

    const deadline = Date.now() + REPLY_WAIT_S * 1000;
    let done = false;
    while (!done && Date.now() < deadline) {
      await sleep(4_000);
      const now = await thread();
      if (answersIn(now) > have) done = true;
      else if (failuresIn(now) > failed) break;
    }
    if (done) console.log('  answered');
    else {
      unanswered++;
      console.error(`  ✗ no answer within ${REPLY_WAIT_S}s (or the turn failed)`);
    }
  }

  if (unanswered) {
    console.error(`✗ ${unanswered} question(s) never got an answer.`);
    console.error('  Is server/api running? The turn is a workflow on the member queue, and it needs a');
    console.error('  working chat key. A thread of unanswered questions is worse than no thread.');
    process.exit(1);
  }
  const end = await thread();
  console.log(`✓ member chat seeded: ${answersIn(end)} answer(s) from ${end.agent?.name ?? 'the team responder'}`);
}

main().catch((err) => {
  console.error('✗ seed-member-chat failed:', err instanceof Error ? err.message : err);
  process.exit(1);
});
