/**
 * Seed the Team Forum: a member asks the brain real questions, and the brain
 * answers them for real.
 *
 * The forum is the one team surface where the brain does visible work, so the
 * answers here are GENERATED by an actual agent turn rather than written by
 * hand. That is the same choice the rest of the demo made — the 1489 traces and
 * 442 assistant messages are real turns, not fabricated transcripts — and it is
 * the only version worth showing, because a demo whose pitch is "watch the
 * brain work" cannot fake the working.
 *
 * REQUIREMENTS, all of which fail loudly rather than producing empty topics:
 *   - a WRITABLE server/web (the serve-time reader cannot post)
 *   - server/api running: the forum turn is a DBOS job on the FORUM_QUEUE, and
 *     without that process the topic is created and no answer ever arrives
 *   - a real chat key on the brain (seeded at onboarding), or the turn fails
 *   - DEMO_TEAM_COOKIE: posting is a MEMBER action, so this speaks as the
 *     member enable-team.ts enrolled, not as the owner
 *
 *   DEMO_TEAM_COOKIE=$(… mint-team-cookie.ts) \
 *     pnpm -C server/web exec tsx ../../demo/seed/seed-forum.ts
 */
const SERVER = process.env.DEMO_SERVER_URL ?? 'http://127.0.0.1:3902';
const TEAM_COOKIE = process.env.DEMO_TEAM_COOKIE ?? '';
/** Seconds to wait for each agent answer before giving up on it. */
const REPLY_WAIT_S = Number(process.env.DEMO_FORUM_REPLY_WAIT ?? 180);

/**
 * Questions a member of THIS studio would actually ask, each answerable from
 * seeded content — so the answers demonstrate retrieval rather than the model's
 * general knowledge. Deterministic and ordered: the forum should look the same
 * after every re-seed.
 */
const TOPICS: { title: string; body: string; kind: 'question' | 'discussion' }[] = [
  {
    title: 'Which pumphouse procedure revision is current?',
    body: "I'm heading to the pumphouse tomorrow and want to be sure I'm working to the right revision. Which one supersedes the others, and what actually changed between them?",
    kind: 'question',
  },
  {
    title: 'What should I check before a loop calibration visit?',
    body: 'Putting my kit together for a site visit. What does the handbook say I need to confirm before I leave, and what invalidates a calibration once I am there?',
    kind: 'question',
  },
  {
    title: 'Where did the storefront snags land?',
    body: 'Catching up on the storefront tranche. Which snags are still open, and is anything waiting on the client rather than on us?',
    kind: 'question',
  },
  {
    title: 'Naming for the island drawings',
    body: 'Starting the island research drawings this week. Worth agreeing the naming up front so we are not renaming files later — what convention are we on now?',
    kind: 'question',
  },
];

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function api(path: string, init: RequestInit = {}) {
  return fetch(`${SERVER}${path}`, {
    ...init,
    headers: {
      'content-type': 'application/json',
      cookie: `mantle_team_chat=${TEAM_COOKIE}`,
      ...(init.headers ?? {}),
    },
  });
}

type Topic = { id: string; title: string; postCount?: number; posts?: unknown[] };

async function listTopics(): Promise<Topic[]> {
  const res = await api('/api/team/forum/topics');
  if (!res.ok) return [];
  const body = (await res.json().catch(() => ({}))) as { topics?: Topic[] };
  return body.topics ?? [];
}

/**
 * Has the agent's answer actually LANDED?
 *
 * Not "is there more than one post": the agent's post is created immediately
 * with status 'pending' and an empty body, and filled in when the turn
 * finishes. Counting posts therefore reports success the instant the question
 * is asked, which is precisely the kind of check that passes over unfinished
 * work. Require an agent post that is complete AND has text in it.
 */
type Post = { authorKind?: string; status?: string; body?: string };
async function answered(id: string): Promise<boolean> {
  const res = await api(`/api/team/forum/topics/${id}`);
  if (!res.ok) return false;
  const body = (await res.json().catch(() => ({}))) as { posts?: Post[] };
  return (body.posts ?? []).some(
    (p) => p.authorKind === 'agent' && p.status === 'complete' && (p.body ?? '').trim().length > 0,
  );
}

async function main() {
  if (!TEAM_COOKIE) {
    console.error('✗ DEMO_TEAM_COOKIE is required — posting to the forum is a MEMBER action.');
    console.error('  Mint it with demo/seed/mint-team-cookie.ts (needs a member: enable-team.ts).');
    process.exit(1);
  }

  // Fail early and clearly rather than creating topics nobody answers.
  const probe = await api('/api/team/forum/topics');
  if (probe.status === 401) {
    console.error('✗ the team cookie was refused — is the contact still a live team member?');
    process.exit(1);
  }
  if (!probe.ok) {
    console.error(`✗ forum unreachable: ${probe.status} ${(await probe.text()).slice(0, 160)}`);
    process.exit(1);
  }

  const existing = new Set((await listTopics()).map((t) => t.title));
  const created: { id: string; title: string }[] = [];

  for (const t of TOPICS) {
    if (existing.has(t.title)) {
      console.log(`· "${t.title}" — already there`);
      continue;
    }
    // 6 posts / 60s per contact. Pace rather than race, and treat a 429 as
    // something to wait out rather than a failure.
    for (let attempt = 0; attempt < 3; attempt++) {
      const res = await api('/api/team/forum/topics', {
        method: 'POST',
        body: JSON.stringify({ title: t.title, body: t.body, kind: t.kind, visibility: 'team' }),
      });
      if (res.status === 429) {
        const wait = Number(res.headers.get('Retry-After') ?? 20);
        console.log(`  rate limited — waiting ${wait}s`);
        await sleep((wait + 1) * 1000);
        continue;
      }
      if (!res.ok) {
        console.error(`✗ create failed for "${t.title}": ${res.status} ${(await res.text()).slice(0, 200)}`);
        process.exit(1);
      }
      // The endpoint answers { topicId, postId } — an earlier version of this
      // script looked for `topic.id`, captured nothing, and then reported
      // success without ever waiting for a single answer.
      const body = (await res.json().catch(() => ({}))) as { topicId?: string };
      if (!body.topicId) {
        console.error(`✗ created "${t.title}" but no topicId came back — cannot verify the answer.`);
        process.exit(1);
      }
      created.push({ id: body.topicId, title: t.title });
      console.log(`· asked: ${t.title}`);
      break;
    }
    await sleep(11_000); // stay comfortably inside the burst window
  }

  // Wait on EVERY seeded topic, not only the ones created on this run: a
  // re-run after a half-finished seed must still notice unanswered questions
  // rather than skipping straight past them.
  const wanted = new Set(TOPICS.map((t) => t.title));
  const all = (await listTopics()).filter((t) => wanted.has(t.title));
  if (!all.length) {
    console.error('✗ no seeded topics found after posting — nothing to wait on.');
    process.exit(1);
  }

  // The answers are the point. Wait for them, and say so plainly if they never
  // arrive — a forum of unanswered questions is worse than no forum, and it
  // would otherwise look like success in this script's output.
  console.log(`→ waiting up to ${REPLY_WAIT_S}s for the brain to answer ${all.length} topic(s)`);
  const deadline = Date.now() + REPLY_WAIT_S * 1000;
  const pending = new Map(all.map((t) => [t.id, t.title]));
  while (pending.size && Date.now() < deadline) {
    for (const [id, title] of [...pending]) {
      if (await answered(id)) {
        pending.delete(id);
        console.log(`  answered: ${title}`);
      }
    }
    if (pending.size) await sleep(5_000);
  }

  if (pending.size) {
    console.error(`✗ ${pending.size} topic(s) never got an answer:`);
    for (const title of pending.values()) console.error(`    ${title}`);
    console.error('  Is server/api running? The forum turn is a DBOS job on the forum queue,');
    console.error('  and without that process the topic exists with nobody to answer it.');
    process.exit(1);
  }
  console.log(`✓ forum seeded: ${all.length} topic(s), every one answered by the brain`);
}

main().catch((err) => {
  console.error('✗ seed-forum failed:', err instanceof Error ? err.message : err);
  process.exit(1);
});
